# app config
javaHome : 
osType : 
fileUploadSize: -1
fileUploadSizePerFile : -1
fileUploadMaxInMemorySize: 5242880
protocol: http
hostname: localhost
port : 12346
contextPath : /vtool
schedulerEnable: false

# db config
db:
  type : h2
  url : jdbc:h2:file:#resourePath#/db/vartool;AUTO_SERVER=TRUE;CACHE_SIZE=131072;
  username : sa
  password : sa
  driverClass : org.h2.Driver
#  maxTotal: 10
#  minIdle: 2
#  maxIdle: 10
#  initialSize: 3
#  maxWaitMillis: 50000
#  validationQuery: select 1
#  testWhileIdle: true
  

# password config
passwordConfig:
  crpyto : aes
  secretKey : MTZkNzMwM2QtMDQ4NS0zOTlhLWEyZmMtODAwNTg0NDY0NzZk
# customClass :
  
userPassowrdResetConfig:
  mode: email #default manager, email
  size: 8 
  type: LOWER_AND_VNUMBER 
 
# mail config
mail :
#  host : emailAddress
#  port : 25
#  username : username
#  password : password
#  fromEmail : noreply@vartool.com
#  smtpAuth : true
#  transportProtocol : smtp
#  starttlsEnable : true 


# deply config
deploy:
  sourcePath :
  defaultDependencyPath : C:/0.server/apache-tomcat-8.5.54/lib
  antExeFile : C:/zzz/apache-ant-1.10.2/bin/ant.bat
  gradleExeFile : C:/zzz/apache-ant-1.10.2/bin/ant.bat
  buildFileCreatePath :
  

   


